apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: py-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi