apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: py-app
  labels:
    app: fastapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi